services:
  db:
    extends:
      file: docker-compose.db.yml
      service: db

  memory-proxy:
    extends:
      file: docker-compose.proxy.yml
      service: memory-proxy
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
